### ISSUE TITLE
S3 이미지 CORS 오류

### ISSUE THREAD

**Issue by yoonth95** [FESP-TEAM-1/beta-frontend#135]
### ❗️checklist

- [x] labels
- [x] assignees

<br>

## 🤔 문제

![image](https://github.com/FESP-TEAM-1/beta-frontend/assets/78673090/674a4365-1fef-4a70-8c91-f9d6df258ae5)

- 게시글 수정 페이지에서 기존에 저장된 이미지를 불러오는 과정에서 AWS S3 버킷에 저장된 이미지를 불러옴
- 메인 이미지의 경우 컬러를 추출해야 되기 때문에 color-thief-react 라이브러리를 사용
- S3에서 불러온 이미지의 컬러를 추출하는 과정에서 CORS 오류가 발생

<br>

### 1. S3 버킷 CORS 정책 (아래의 사진처럼 설정 값을 모든 출처에서의 요청을 허용했기 때문에 이는 문제가 아님)
<img src="https://github.com/FESP-TEAM-1/beta-frontend/assets/78673090/8423706d-b557-4d04-8b09-299d20311584" width='500' />

- **`Access-Control-Allow-Headers`**: 허용할 헤더를 지정하거나 모든 헤더를 허용하려면 `*`
- **`Access-Control-Allow-Methods`**: 허용할 HTTP 메서드를 지정합니다.
    
    모든 메서드를 허용하려면 **`GET, POST, PUT, DELETE, OPTIONS`** 등을 지정
    
- **`Access-Control-Allow-Origin`**: 허용할 특정 도메인을 지정하거나 모든 도메인을 허용하려면  `*`
- **`Access-Control-Expose-Headers`**: 브라우저가 접근할 수 있게 하려는 헤더를 지정
    
    모든 헤더를 노출 시키지 않으려면 이 필드를 비워두거나, 특정 헤더만 지정

### 2. 캐싱
- S3 이미지 응답에 오래된 CORS 설정이 포함되어 있어, 새로운 설정이 반영되지 않았음

<br>

### 캐시 우회
- 이미지 태그의 `src` 속성에 타임 스탬프를 쿼리 파라미터로 추가 (_아래의 이미지 참고_)
- 각 요청의 URL을 고유하게 만들어 브라우저가 새로운 요청으로 인식하게 하여 캐시를 우회

![image](https://github.com/FESP-TEAM-1/beta-frontend/assets/78673090/34a762f8-8245-4b32-8b41-04cbce005f06)

### 무한 리렌더링
- 캐시 우회까지는 맞는데, React에서는 URL이 계속 변경이 되어 새로운 값으로 인식하고 컴포넌트를 무한 리렌더링 하는 문제 발생
- 이를 방지하기 위해 `useRef` Hook을 사용하여 타임 스탬프 값을 넣고 값이 변경되어도 리렌더링이 발생하지 않음

```
const timestamp = useRef(new Date().getTime()).current;

{imgExistingUrls &&
  imgExistingUrls.map((image) => (
    <li key={image}>
      <div className={styles["img-cover"]}>
        <img src={import.meta.env.VITE_APP_IMAGE_DOMAIN + image + "?" + timestamp} alt="" />
        <DeleteButton spanHidden="해당 이미지 삭제" onClick={() => handleRemoveExistingImage(image)} forImage />
      </div>
    </li>
  ))}
```

<br>

## 🎸 기타 (느낀점, 참고자료 등)

이 문제는 S3에서 가져온 이미지를 파일로 변환을 한다거나 canvas로 새로운 값으로 이미지를 재생성 하려고 할 때도 발생하는 문제입니다. 여러 블로그나 참고 글을 봤는데, img 태그에 crossorigin="anonymous" 속성 값을 넣는 다거나 이미지 태그가 아닌 css background url을 넣는다는 글이 많은데 결국은 해결이 되지 않습니다.
캐시 우회하는 방법이 제일 좋은 방법이라고 생각합니다.

파일로 변환하거나 canvas로 새로 그리거나 html2canvas 같은 이미지를 참고해야 하는 데이터 URI 방식은 캐시 우회가 불필요하기 때문에 URI / URL 둘 다 사용할 경우는 아래의 코드를 사용하면 됩니다.
`img.src = /^data:image/.test(src) ? src : src + '?' + new Date().getTime();`

**Comment by ebokyung** [comment]
cors 관련해서 잘 몰라서 그런지 어렵네요 🥲 

1. 일단 문제가
만약 S3에 저장된 기존 이미지를 2개(src-a 와 src-b라고 가정)를 가져온다면 
src-a 이미지를 화면상에서 지우고, src-b가 메인 이미지로 변경 됐을 때
color-thief 라이브러리가 src-b에 접근하는 데서 막힌다고 이해했는데 맞을까요?

2. 이때 원인은 
S3 설정 문제가 아니라 캐싱 관련인데 ... 여기가 이해가 잘 안됩니다 ㅠ
    > S3 이미지 응답에 오래된 CORS 설정이 포함되어 있어, 새로운 설정이 반영되지 않았음

    혹시 여기 부분 조금 더 자세하게 설명 부탁드려도 될까요?
    S3에 저장된 이미지를 처음에 가지고 오고난 뒤, 색깔을 추출하기 위해 다시 이미지에 접근하고자 할때 
    처음 요청에서 설정한 cors 설정 때문에 막힌다는 의미일까요? 
    맞다면 처음 요청에 설정한 cors와 다시 요청했을때 cors 설정이 어떤 점에서 달라서 막히는 건지 궁금해요

<br/>

3. 그리고 기타 부분에서 적어주신 부분도 여쭤보고자 하는게 있어요.
S3에서 가져온 `이미지를 파일로 변환`을 한다거나 canvas로 `새로운 값으로 이미지를 재생성`하려고 할 때 (CORS 에러)발생한다고 하셨는데, 그 다음 문단에서 `파일로 변환`하거나 `canvas로 새로 그리거나` html2canvas 같은 `이미지를 참고`해야 하는 데이터 URI 방식과 어떤 경우에서 다르다고 하는 건지 잘 모르겠어요. ㅜㅜㅜ 

설명이 길다면 참고하신 자료를 공유해주셔도 좋을 것 같습니다 :)
